services:
  # ASP.NET Web API service
  webapi:
    image: mcr.microsoft.com/dotnet/aspnet:8.0 # Use the appropriate .NET version
    container_name: aspnet_webapi
    build:
      context: ./webapi # This should point to your Web API project folder
      dockerfile: Dockerfile # Make sure there's a Dockerfile in this folder
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
    ports:
      - "7294:8080" # Expose Web API on port 7294

